from collections.abc import Mapping, Sequence

class Remote:
    def __init__(self, uri: str) -> None: ...
    def get_keyword_names(self) -> list[str]: ...
    def run_keyword(
        self,
        name: str,
        args: Sequence[object],
        kwargs: Mapping[str, object],
    ) -> object: ...
    def get_keyword_documentation(self, name: str) -> str: ...
    def get_keyword_arguments(self, name: str) -> list[str]: ...
